# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-16 21:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(max_length=15)),
                ('valid', models.BooleanField(default=True)),
                ('user_marking_invalid', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('respondent_wave', models.CharField(choices=[('W1', 'Wave One'), ('W2', 'Wave Two'), ('W3', 'Wave Three')], default='W1', max_length=2)),
                ('done_online_survey', models.BooleanField(default=False)),
                ('call_one', models.BooleanField(default=False)),
                ('call_one_time', models.DateTimeField(verbose_name='time of first call')),
                ('call_one_user', models.CharField(max_length=80)),
                ('call_two', models.BooleanField(default=False)),
                ('call_two_time', models.DateTimeField(verbose_name='time of second call')),
                ('call_two_user', models.CharField(max_length=80)),
                ('call_three', models.BooleanField(default=False)),
                ('call_three_time', models.DateTimeField(verbose_name='time of third call')),
                ('call_three_user', models.CharField(max_length=80)),
                ('call_one_phone', models.ManyToManyField(related_name='_voter_call_one_phone_+', to='voters.Phone')),
                ('call_three_phone', models.ManyToManyField(related_name='_voter_call_three_phone_+', to='voters.Phone')),
                ('call_two_phone', models.ManyToManyField(related_name='_voter_call_two_phone_+', to='voters.Phone')),
                ('phone_no_one', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone number one+', to='voters.Phone')),
                ('phone_no_two', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone number two+', to='voters.Phone')),
            ],
        ),
    ]
