# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='respondent_age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voter',
            name='respondent_id',
            field=models.CharField(default=None, max_length=15),
        ),
    ]
