# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-18 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0002_auto_20160918_1221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='user_marking_invalid',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_one_phone',
            field=models.ManyToManyField(blank=True, related_name='_voter_call_one_phone_+', to='voters.Phone'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_one_time',
            field=models.DateTimeField(blank=True, verbose_name='time of first call'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_one_user',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_three_phone',
            field=models.ManyToManyField(blank=True, related_name='_voter_call_three_phone_+', to='voters.Phone'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_three_time',
            field=models.DateTimeField(blank=True, verbose_name='time of third call'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_three_user',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_two_phone',
            field=models.ManyToManyField(blank=True, related_name='_voter_call_two_phone_+', to='voters.Phone'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_two_time',
            field=models.DateTimeField(blank=True, verbose_name='time of second call'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_two_user',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='voter',
            name='phone_no_one',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone number one+', to='voters.Phone'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='phone_no_two',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone number two+', to='voters.Phone'),
        ),
    ]
