# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0004_auto_20160918_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='voter',
            name='call_one_outcome',
            field=models.CharField(blank=True, choices=[('LV', 'Left Voicemail'), ('NH', 'Not Home'), ('CB', 'Requested Call Back'), ('LV', 'Left a Voicemail'), ('SD', 'Soft Decline'), ('HD', 'Hard Decline')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='call_three_outcome',
            field=models.CharField(blank=True, choices=[('LV', 'Left Voicemail'), ('NH', 'Not Home'), ('CB', 'Requested Call Back'), ('LV', 'Left a Voicemail'), ('SD', 'Soft Decline'), ('HD', 'Hard Decline')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='voter',
            name='call_two_outcome',
            field=models.CharField(blank=True, choices=[('LV', 'Left Voicemail'), ('NH', 'Not Home'), ('CB', 'Requested Call Back'), ('LV', 'Left a Voicemail'), ('SD', 'Soft Decline'), ('HD', 'Hard Decline')], max_length=2, null=True),
        ),
    ]
