# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-19 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0005_auto_20160918_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='call_one_outcome',
            field=models.CharField(blank=True, choices=[('TS', 'Respondent took the Survey'), ('NH', 'Not Home'), ('CB', 'Requested Call Back'), ('LV', 'Left a Voicemail'), ('SD', 'Soft Decline'), ('HD', 'Hard Decline')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_three_outcome',
            field=models.CharField(blank=True, choices=[('TS', 'Respondent took the Survey'), ('NH', 'Not Home'), ('CB', 'Requested Call Back'), ('LV', 'Left a Voicemail'), ('SD', 'Soft Decline'), ('HD', 'Hard Decline')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_two_outcome',
            field=models.CharField(blank=True, choices=[('TS', 'Respondent took the Survey'), ('NH', 'Not Home'), ('CB', 'Requested Call Back'), ('LV', 'Left a Voicemail'), ('SD', 'Soft Decline'), ('HD', 'Hard Decline')], max_length=2, null=True),
        ),
    ]
