# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-01 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0007_auto_20161001_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_no',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='voter',
            name='respondent_id',
            field=models.CharField(default=None, max_length=25, null=True),
        ),
    ]
