# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-16 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0010_voter_last_display_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='respondent_age',
            field=models.CharField(default='0', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='respondent_wave',
            field=models.CharField(choices=[('W1', 'Wave One'), ('W2', 'Wave Two'), ('W3', 'Wave Three'), ('W4', 'Wave Four')], default='W1', max_length=2),
        ),
    ]
