# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-23 19:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0012_auto_20161022_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='call_five_phone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone for call five+', to='voters.Phone'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_five_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time of fifth call'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_seven_phone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone for call seven+', to='voters.Phone'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_seven_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time of seventh call'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_six_phone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone for call six+', to='voters.Phone'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='call_six_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time of sixth call'),
        ),
        migrations.AlterField(
            model_name='voter',
            name='supervisor_hold_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='On Hold Until:'),
        ),
    ]
