# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-06 15:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voters', '0013_auto_20161023_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='respondent_wave',
            field=models.CharField(choices=[('W1', 'Wave One'), ('W2', 'Wave Two'), ('W3', 'Wave Three'), ('W4', 'Wave Four'), ('W5', 'Wave Five')], default='W1', max_length=2),
        ),
    ]
